// One-time/dev tool: self-host the web fonts so we can drop the render-blocking
// Google Fonts <link>. Downloads the latin + latin-ext woff2 subsets (covers
// EN + ES; Devanagari is skipped) into public/fonts/ and writes src/styles/
// fonts.css with @font-face rules pointing at the local files. Re-run to refresh.
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Marcellus+SC&family=Rajdhani:wght@400;500;600;700&display=swap'
const KEEP = new Set(['latin', 'latin-ext'])

const fontsDir = fileURLToPath(new URL('../public/fonts/', import.meta.url))
mkdirSync(fontsDir, { recursive: true })

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g
let out =
  '/* Self-hosted fonts (latin + latin-ext) — generated by scripts/fetch-fonts.mjs.\n' +
  '   Replaces the render-blocking Google Fonts <link>. Re-run to refresh. */\n\n'
let count = 0
for (const m of css.matchAll(blockRe)) {
  const subset = m[1]
  if (!KEEP.has(subset)) continue
  let block = m[2]
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1]
  const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || '400'
  const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1]
  if (!fam || !url) continue
  const fname = `${slug(fam)}-${weight}-${subset}.woff2`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  writeFileSync(fileURLToPath(new URL(fname, `file://${fontsDir}`)), buf)
  out += block.replace(url, `/fonts/${fname}`) + '\n\n'
  count++
}
writeFileSync(fileURLToPath(new URL('../src/styles/fonts.css', import.meta.url)), out)
console.log(`[fetch-fonts] saved ${count} woff2 files + src/styles/fonts.css`)
